name: Gh-Pages

on:
  push:
    branches: [ master, add-post-with-gh-pages ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          webRenderer: canvaskit
          baseHref: /flame_game_jam_dexters/

